### ISSUE TITLE
docs?

### ISSUE THREAD

**Issue by lua-vr** [flupe/achille#1]
Hi, the documentation website seems to be unavailable. Also, there is no snapshot of its subpages in the internet archive. If this is not a temporary problem, maybe you can organize the docs somewhere else?

Thanks!

**Comment by flupe** [comment]
Hello!
Yes, this site is (was) self-hosted but our server has been under maintenance for the past 2 weeks. This issue should be resolved next weekend, but you're right I should look into putting the docs somewhere else, perhaps simply on Hackage.

**Comment by lua-vr** [comment]
Just found out the website's source is available at https://github.com/flupe/site --- in the meanwhile I can read the documentation there, so no worries 🙂 and I'll be closing this issue.

**Comment by flupe** [comment]
Ah yes, completely forgot the source was available!
Although I have to be honest, I made some changes to the library and did not update the documentation, so some of it might be out of date by now.

The most noteworthy breaking change I can think of is the removal of the `Recipe` type family. `Recipe m a b` would just be `a -> Task m b` in the current version of the library (not uploaded to Hackage yet, but on the master branch of the repo).

Don't hesitate to ask questions if you need some pointers, pretty sure I'm the only user of this library so I haven't spent that much time documenting it and making it comprehensible.
And if you need a similar, more robust and maintained alternative, you might have better luck with [Ema](https://ema.srid.ca/), made by the creator of [Rib](https://hackage.haskell.org/package/rib), which I just found out about (Although I *do* feel like `achille` is useful :slightly_smiling_face:)

**Comment by lua-vr** [comment]
Interesting, thanks for the info! For now I'm just reading about a few alternatives supporting pandoc. I want to add a nice display of `org-roam` notes (an emacs thing) in my blog and for that I would have to do some manipulation on what's parsed by pandoc and maybe generate new pages based on that. I know very little Haskell so this is also a long term project for me to learn more about the language.
